/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AudioPreview: typeof import('./src/components/AudioPreview.vue')['default']
    ColorMgr: typeof import('./src/components/ColorMgr.vue')['default']
    ColorPicker: typeof import('./src/components/ColorPicker.vue')['default']
    FabButton: typeof import('./src/components/FabButton.vue')['default']
    GConfig: typeof import('./src/components/GConfig.vue')['default']
    IconMdiCheckAll: typeof import('~icons/mdi/check-all')['default']
    RewardListPop: typeof import('./src/components/RewardListPop.vue')['default']
    RewardPop: typeof import('./src/components/RewardPop.vue')['default']
    RewardSet: typeof import('./src/components/RewardSet.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerRemoteBadge: typeof import('./src/components/ServerRemoteBadge.vue')['default']
    XunfeiIat: typeof import('./src/components/XunfeiIat.vue')['default']
  }
}
