/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CalendarCover: typeof import('./src/components/CalendarCover.vue')['default']
    CalendarTab: typeof import('./src/components/CalendarTab.vue')['default']
    ChatSetting: typeof import('./src/components/ChatSetting.vue')['default']
    ColorMgr: typeof import('./src/components/ColorMgr.vue')['default']
    ColorPicker: typeof import('./src/components/ColorPicker.vue')['default']
    ColorSelector: typeof import('./src/components/ColorSelector.vue')['default']
    copy: typeof import('./src/components/RewardSet copy.vue')['default']
    FabButton: typeof import('./src/components/FabButton.vue')['default']
    GConfig: typeof import('./src/components/GConfig.vue')['default']
    GroupSelector: typeof import('./src/components/GroupSelector.vue')['default']
    IconMdiAccount: typeof import('~icons/mdi/account')['default']
    IconMdiCalendarTodayOutline: typeof import('~icons/mdi/calendar-today-outline')['default']
    IconMdiCheckAll: typeof import('~icons/mdi/check-all')['default']
    IconMdiListStatus: typeof import('~icons/mdi/list-status')['default']
    IconMdiRomanNumeral7: typeof import('~icons/mdi/roman-numeral7')['default']
    PrioritySelector: typeof import('./src/components/PrioritySelector.vue')['default']
    RepeatSelector: typeof import('./src/components/RepeatSelector.vue')['default']
    RewardPop: typeof import('./src/components/RewardPop.vue')['default']
    RewardSet: typeof import('./src/components/RewardSet.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchedulePopModal: typeof import('./src/components/SchedulePopModal.vue')['default']
    SubtaskPopModal: typeof import('./src/components/SubtaskPopModal.vue')['default']
    WeekSelector: typeof import('./src/components/WeekSelector.vue')['default']
    XunfeiIat: typeof import('./src/components/XunfeiIat.vue')['default']
  }
}
