/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CalendarCover: typeof import('./src/components/CalendarCover.vue')['default']
    CalendarTab: typeof import('./src/components/CalendarTab.vue')['default']
    ColorSelector: typeof import('./src/components/ColorSelector.vue')['default']
    GConfig: typeof import('./src/components/GConfig.vue')['default']
    GroupSelector: typeof import('./src/components/GroupSelector.vue')['default']
    IconMdiAccount: typeof import('~icons/mdi/account')['default']
    IconMdiCalendarTodayOutline: typeof import('~icons/mdi/calendar-today-outline')['default']
    IconMdiCheckAll: typeof import('~icons/mdi/check-all')['default']
    IconMdiListStatus: typeof import('~icons/mdi/list-status')['default']
    'IconMdiRomanNumeral-': typeof import('~icons/mdi/roman-numeral-')['default']
    IconMdiRomanNumeral1: typeof import('~icons/mdi/roman-numeral1')['default']
    IconMdiRomanNumeral2: typeof import('~icons/mdi/roman-numeral2')['default']
    IconMdiRomanNumeral7: typeof import('~icons/mdi/roman-numeral7')['default']
    IconMdiTag: typeof import('~icons/mdi/tag')['default']
    IconMidCalendarTodayOutline: typeof import('~icons/mi/d-calendar-today-outline')['default']
    IconMidCheckAll: typeof import('~icons/mi/d-check-all')['default']
    IconMidListStatus: typeof import('~icons/mi/d-list-status')['default']
    IconMidTag: typeof import('~icons/mi/d-tag')['default']
    PrioritySelector: typeof import('./src/components/PrioritySelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchedulePopModal: typeof import('./src/components/SchedulePopModal.vue')['default']
    SubtaskPopModal: typeof import('./src/components/SubtaskPopModal.vue')['default']
  }
}
